name: fpe
version: 0.1.0
synopsis: Format-preserving encryption.
maintainer: Galen Huntington
category: Cryptography

github: galenhuntington/fpe

ghc-options: -Wall -Wredundant-constraints -Wno-name-shadowing -Wno-missing-signatures -Wno-unused-do-bind -Wno-orphans -Wcompat

source-dirs:
   - .

default-extensions:
   - TypeApplications
   - ScopedTypeVariables

library: {}

dependencies:
   - base >= 4.9 && < 5
   - bytestring >= 0.10 && < 0.11
   - vector >= 0.12 && < 0.13
   - integer-logarithms >= 1 && < 1.1

tests:
   suite:
      main: ff1test.hs
      dependencies:
         - cryptonite

