name: fpe
version: 0.1.0
synopsis: Format-preserving encryption.
maintainer: Galen Huntington
license: MIT
category: Cryptography

ghc-options: -O2 -Wall -Wredundant-constraints -Wno-name-shadowing -Wno-missing-signatures -Wno-unused-do-bind -Wno-orphans -Wcompat

source-dirs:
   - .

default-extensions:
   - TypeApplications
   - ScopedTypeVariables

library: {}

dependencies:
   - base
   - bytestring
   - vector
   - integer-logarithms

tests:
   suite:
      main: ff1test.hs
      dependencies:
         - cryptonite

