on: [push]
name: build
jobs:
  cabal:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        ghc: ['8.4', '9.4', 'latest']
    name: GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal test
  stack:
    runs-on: 'ubuntu-latest'
    name: Stack
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      - run: stack test

